language: go

go:
  - 1.13.x
env:
  - GO111MODULE=on

script: go get -v

before_deploy: make build-all

deploy:
  provoder: releases
  api_key: $API_KEY
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    repo: jaydenwen123/Somusic
    tags: true
